import {beforeEach,describe,expect,it,vi} from 'vitest';
const state=vi.hoisted(()=>({notification:{id:'notification',recipient_email:'customer@example.test',template:'hosting_started',prepared_email:{subject:'Frozen original',to:'customer@example.test'},payload:{},attempts:1},claim:true,readError:false,saveError:false,send:vi.fn(),prepare:vi.fn(),rpc:vi.fn()}));
vi.mock('@/lib/email',()=>({prepareHostingEmail:state.prepare,sendPreparedHostingEmail:state.send}));
vi.mock('@/lib/supabase',()=>({createServerClient:()=>({from:()=>{const query:Record<string,unknown>={};for(const key of ['select','eq','in','lte','order','limit'])query[key]=()=>query;query.maybeSingle=async()=>({data:state.notification,error:state.readError?{message:'offline'}:null});return query;},rpc:state.rpc})}));
import {deliverHostingNotification} from './hosting-notifications';
describe('durable hosting notification delivery',()=>{
 beforeEach(()=>{vi.clearAllMocks();state.claim=true;state.readError=false;state.saveError=false;state.send.mockResolvedValue({id:'provider-id'});state.rpc.mockImplementation(async(name:string,args:Record<string,unknown>)=>name==='claim_hosting_notification'?{data:state.claim?{lease_token:'lease',prepared_email:state.notification.prepared_email}:null,error:null}:{error:state.saveError&&args.p_provider_id?{message:'offline'}:null});});
 it('reuses the frozen message instead of rebuilding from mutable subscription state',async()=>{await deliverHostingNotification('subscription');expect(state.prepare).not.toHaveBeenCalled();expect(state.send).toHaveBeenCalledWith(state.notification.prepared_email,'notification');expect(state.rpc).toHaveBeenLastCalledWith('finish_hosting_notification',{p_id:'notification',p_lease:'lease',p_provider_id:'provider-id',p_error:null});});
 it('does not send when another worker owns the lease or review is required',async()=>{state.claim=false;await deliverHostingNotification('subscription');expect(state.send).not.toHaveBeenCalled();});
 it('preserves recovery when provider acceptance cannot be persisted',async()=>{state.saveError=true;await expect(deliverHostingNotification('subscription')).rejects.toThrow('requires reconciliation');expect(state.send).toHaveBeenCalledTimes(1);expect(state.rpc).toHaveBeenLastCalledWith('finish_hosting_notification',expect.objectContaining({p_lease:'lease',p_provider_id:null,p_error:expect.stringContaining('requires reconciliation')}));});
 it('never reports an unavailable outbox as successfully drained',async()=>{state.readError=true;await expect(deliverHostingNotification('subscription')).rejects.toThrow('queue unavailable');expect(state.send).not.toHaveBeenCalled();});
});
