-- Cival Systems commerce schema
--
-- This file is intentionally non-executable. The old all-in-one schema granted
-- public access to download rows and must not be used.
--
-- Apply every SQL file in src/migrations in numeric order. New installations
-- start at 001_initial_schema.sql. Existing installations that already have the
-- four base commerce tables start with the next unapplied migration.
--
-- All migrations should be run through the Supabase migration workflow and
-- reviewed in a transaction before production application.
